---
#
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

  - name: 5.2.1.1 Configure Audit Log Storage Size (Not Scored)
    shell: grep max_log_file "{{auditdconf}}"
    changed_when: false
    ignore_errors: true
    tags:
      - notscored
      - section5.2
      - section5.2.1
      - section5.2.1.1

  - name: 5.2.1.2 Disable System on Audit Log Full (Not Scored)
    shell: grep admin_space_left_action "{{auditdconf}}"
    changed_when: false
    ignore_errors: true
    tags:
      - notscored
      - section5.2
      - section5.2.1
      - section5.2.1.2

  - name: 5.2.1.2 Disable System on Audit Log Full (Not Scored)
    shell: grep space_left_action "{{auditdconf}}"
    changed_when: false
    ignore_errors: true
    tags:
      - notscored
      - section5.2
      - section5.2.1
      - section5.2.1.2

  - name: 5.2.1.2 Disable System on Audit Log Full (Not Scored)
    shell: grep action_mail_acct "{{auditdconf}}"
    changed_when: false
    ignore_errors: true
    tags:
      - notscored
      - section5.2
      - section5.2.1
      - section5.2.1.2

  - name: 5.2.1.3 Keep All Auditing Information (Scored)
    shell: grep max_log_file_action "{{auditdconf}}"
    register: out5213
    changed_when: false
    ignore_errors: true
    failed_when: >
      'keep_logs' not in out5213.stdout
    tags:
      - scored
      - section5.2
      - section5.2.1
      - section5.2.1.3

  - name: 5.2.2 Enable auditd Service (Scored)
    shell: chkconfig --list auditd
    register: out522
    changed_when: false
    ignore_errors: true
    failed_when: >
      '3: on' not in out522.stdout
    tags:
      - scored
      - section5.2
      - section5.2.2

  - name: 5.2.3 Enable Auditing for Processes That Start Prior to auditd (Scored)
    shell: grep kernel "{{grubconf}}"
    register: out523
    changed_when: false
    ignore_errors: true
    failed_when: >
     'audit=1' not in out523.stdout
    tags:
      - scored
      - section5.2
      - section5.2.3


  - shell: grep "{{ item }}" "{{auditd_rules}}"
    register: auditout
    changed_when: false
    ignore_errors: true
    with_items:
      - /etc/group
      - /etc/passwd
      - /etc/shadow
      - /etc/gshadow
      - /etc/security/opasswd
      - /etc/localtime
      - clock_settime
      - adjtimex
      - sethostname
      - setdomainname
      - /etc/issue
      - /etc/issue.net
      - /etc/hosts
      - /etc/sysconfig/network
      - /etc/selinux
      - /var/log/faillog
      - /var/log/lastlog
      - /var/log/talylog
      - /var/run/utmp
      - /var/log/wtmp
      - /var/log/btmp
      - chmod
      - chown
      - lchown
      - fchmod
      - fchown
      - fchmodat
      - fchownat
      - creat
      - open
      - openat
      - truncate
      - ftruncate
      - mount
      - unlink
      - unlinkat
      - rename
      - renameat
      - /etc/sudoers
      - /var/log/sudo.log
      - /sbin/insmod
      - /sbin/rmmod
      - /sbin/modprobe
    tags:
      - scored
      - section5.2
      - section5.2.4
      - section5.2.5
      - section5.2.6
      - section5.2.7
      - section5.2.8
      - section5.2.9
      - section5.2.10
      - section5.2.11
      - section5.2.12
      - section5.2.13
      - section5.2.14
      - section5.2.15
      - section5.2.16
      - section5.2.17

  - name: 5.2.4 - 5.2.17  Configure auditd Rules (Scored)
    debug:
      msg: "{{ auditout.results }}"
    changed_when: false
    ignore_errors: true
    tags:
      - scored
      - section5.2
      - section5.2.4
      - section5.2.5
      - section5.2.6
      - section5.2.7
      - section5.2.8
      - section5.2.9
      - section5.2.10
      - section5.2.11
      - section5.2.12
      - section5.2.13
      - section5.2.14
      - section5.2.15
      - section5.2.16
      - section5.2.17

  - name: 5.2.18 Make the Audit Configuration Immutable (Scored) 
    shell: grep "^-e 2" /etc/audit/audit.rules
    register: out5218
    changed_when: false
    ignore_errors: true
    tags:
      - scored
      - section5.2
      - section5.2.18
